{{- range $name, $c := .Values.components }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: reveal-ai-{{ $name }}
  labels:
    app: reveal-ai
    component: {{ $name }}
spec:
  replicas: {{ $.Values.replicaCount }}
  selector:
    matchLabels:
      app: reveal-ai
      component: {{ $name }}
  template:
    metadata:
      labels:
        app: reveal-ai
        component: {{ $name }}
        reveal-ai/env: {{ $.Values.env | quote }}
        reveal-ai/chart-version: {{ $.Chart.Version | quote }}
    spec:
      containers:
      - name: {{ $name }}
        image: "{{ $c.image.repository }}:{{ $c.image.tag }}"
        {{- if $c.port }}
        ports:
        - name: http
          containerPort: {{ $c.port }}
        {{- end }}
        resources:
          {{- toYaml $.Values.resources | nindent 10 }}
{{- end }}
