apiVersion: v1
kind: Service
metadata:
  name: reveal-ai
  labels:
    app: reveal-ai
spec:
  type: {{ .Values.service.type }}
  selector:
    app: reveal-ai
  ports:
  - name: http
    port: {{ .Values.service.port }}
    targetPort: http
